import { Board } from './types.ts'

export const useBoards = (): Board[] => {
    return [
        {
            id: 0,
            name: 'Classic',
            minPlayers: 3,
            //maxPlayers: 6 sempre
            characters: [
                'Miss Scarlett',
                'Professor Plum',
                'Mrs. Peacock',
                'Reverend Green',
                'Colonel Mustard',
                'Mrs. White',
            ],
            weapons: [
                'Candlestick',
                'Dagger',
                'Lead Pipe',
                'Revolver',
                'Rope',
                'Spanner',
            ],
            rooms: [
                'Kitchen',
                'Ballroom',
                'Conservatory',
                'Dining Room',
                'Billiard Room',
                'Library',
                'Lounge',
                'Hall',
                'Study',
            ],
        },
        {
            id: 1,
            name: 'Meereen',
            minPlayers: 2,
            //maxPlayers: 6 sempre
            characters: [
                'Daenerys',
                'Daario',
                'Missandei',
                'Grey Worm',
                'Loraq',
                'Jorah',
            ],
            weapons: [
                'Poison Vial',
                'Battle Axe',
                'Arokh',
                'Faceless Man',
                'Crossbow',
                'Assassin Dagger',
            ],
            rooms: [
                'Brothel',
                'Pyramid',
                'Slave Quarters',
                'Temple',
                'Dragon Catacombs',
                'Tunnels',
                'Grand Bazaar',
                'City Gates',
                'Pit of Daznak',
            ],
        },
        {
            id: 2,
            name: 'Red Keep',
            minPlayers: 2,
            //maxPlayers: 6 sempre
            characters: [
                'Cersei',
                'Tyrion',
                'Jaime',
                'Margaery',
                'Petyr',
                'Sansa',
            ],
            weapons: [
                'Poison Vial',
                'Battle Axe',
                'Arokh',
                'Faceless Man',
                'Crossbow',
                'Assassin Dagger',
            ],
            rooms: [
                'Council Chamber',
                "Cyburn's Laboratory",
                'Tower of the Hand',
                'Kingsguard Chambers',
                'Prison Cells',
                'Gardens',
                'Pavillion',
                "Townmen's Bedchambers",
                "Pycelle's Lab",
                "Cercei's Bedchambers",
                'Sparring Yard',
            ],
        },
        {
            id: 3,
            name: 'Zelda',
            minPlayers: 2,
            //maxPlayers: 6 sempre
            characters: [
                'Nabooru',
                'Darunia',
                'Zelda',
                'Link',
                'Rauru',
                'Impa',
            ],
            weapons: [
                'Master Sword',
                'Fairy Bow',
                'Megaton Hammer',
                'Boomerang',
                'Hookshot',
                'Bombuchu',
            ],
            rooms: [
                'Death Mountain',
                'Kakariko Village',
                'Lake Hylia',
                'Lost Woods',
                "Zora's Domain",
                'Gerudo Valley',
                'Kokiri Forest',
                'Gerudo Fortress',
                'Sacred Forest Meadow',
            ],
        },
        {
            id: 4,
            name: 'Star Wars',
            minPlayers: 2,
            //maxPlayers: 6 sempre
            characters: [
                'Alderaan',
                'Bespin',
                'Dagobah',
                'Endor',
                'Tatooine',
                'Yavin 4',
            ],
            weapons: [
                'X-Wing',
                'Y-Wing',
                'TIE Fighter',
                'TIE Bomber',
                'Millenium Falcon',
                'Escape Pod',
            ],
            rooms: [
                'War Room',
                'Throne Room',
                'Trash Compactor',
                'Laser Control Room',
                'Docking Bay',
                'Red Control Room',
                'Overbridge',
                'Detention Block',
                'Tractor Beam Generator',
            ],
        },
        {
            id: 5,
            name: 'Harry Potter',
            minPlayers: 3,
            //maxPlayers: 6 sempre
            characters: [
                'Fenrir Greyback',
                'Lucius Malfoy',
                'Peter Pettygrew',
                'Draco Malfoy',
                'Snatcher',
                'Bellatrix Lastrange',
            ],
            weapons: [
                'Jinxed Broomstick',
                'Cursed Necklace',
                'Love Potion',
                'Poisoned Mead',
                'Incedio',
                'Stupefy',
            ],
            rooms: [
                'Malfoy Manor',
                "The Hog's Head",
                'The Shrieking Shack',
                'Hogwarts Castle',
                'Forbidden Coast',
                'Gringotts',
                "Weasleys' Wizard Wheezes",
                'Ministry of Magic',
                '12 Grimmauld Place',
            ],
        },
    ]
}
